### ISSUE TITLE
SquashFS module check

### ISSUE THREAD

**Issue by SPROgster** [dervishe-/genBerry#2]
I have no squashfs module of kernel. Script can't test squashfs image and doesn't copy it to memory card.

**Comment by dervishe-** [comment]
Which distro did you use ? Just install the squashfs tools (for gentoo: emerge squashfs-tools) and if you don't want to compile or add the squashfs kernel module (required for the portage image test) just comment the lines 142 to 153 in the portage2squashfs script

**Comment by dervishe-** [comment]
I've added an option to portage2squash in order to avoid the image test. 
After the end of the imagebuilder script and the failing of the squashfs image test, boot your rPi, go to `/root/tools` and just run the script`portage2squash`. It will build the archive and put it where it belong.
Then you just have to mount /usr/portage directory (just type: `mount /usr/portage`

**Comment by SPROgster** [comment]
I'm talking about squashfs kernel module. My distro is Gentoo
